<?php 
 if(!defined("MYHOST"))
    define("MYHOST","localhost");
  if(!defined("MYUSER"))
    define("MYUSER","16mmi1pj03");
  if(!defined("MYPASS"))
    define("MYPASS","6ELwzacg");
  if(!defined("MYDB"))
    define("MYDB","16mmi1pj03");
?>